import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "./components/menu";
import UserCard from "./components/usercard";

const inter = Inter({ subsets: ["latin"] });
const Loading = () => <div>Carregando...</div>;
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	modal,
}: Readonly<{
	children: React.ReactNode;
	modal: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex bg-gray-500 h-full">
					<div className="flex flex-col gap-5 w-2/12 bg-white p-5">
						<UserCard />
						<Menu />
					</div>
					<div className="flex flex-col w-10/12 justify-start p-5">{children}</div>
				</div>
				{modal}
			</body>
		</html>
	);
}
